packages:
  - packages/**

# 重複排除
dedupePeers: true

catalog:
  rolldown: 1.2.5
  rolldown-plugin-dts: 0.28.2
  turbo: 2.10.12
  typescript: 7.0.2
  valibot: 1.4.2
  vitest: &vitest_ver 4.1.11
  '@biomejs/biome': 2.5.10
  '@fast-check/vitest': 0.4.1
  '@gahojin-inc/aws-lambda-mock-context': 2026.8.0
  '@middy/core': &middy_ver 7.7.2
  '@middy/util': *middy_ver
  '@serverless/event-mocks': 1.1.1
  '@types/aws-lambda': 8.10.162
  '@types/node': 26.3.0
  '@valibot/i18n': 1.2.0
  '@vitest/coverage-v8': *vitest_ver

overrides:
  # CVE-2026-67213
  nanoid: ^3.3.17
  rolldown: 'catalog:'

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880 # 2d
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
