name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".husky/**"
      - ".vscode/**"
      - "LICENSE"
      - "*.md"
      - "bumpver.toml"
  pull_request:
    paths-ignore:
      - ".husky/**"
      - ".vscode/**"
      - "LICENSE"
      - "*.md"
      - "bumpver.toml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip build]') == false

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run biome migrate
        run: pnpm biome migrate --write

      - name: Run Build
        run: pnpm run build

      - name: Check package.json
        run: pnpm run check:packagejson

      - name: Run Linter & Formatter
        run: pnpm run lint

      - name: Run Typescript check
        run: pnpm run check

      - name: Run Unit tests
        run: pnpm run test

      - name: Commit changes
        if: ${{ github.event_name == 'pull_request' }}
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          commit_options: "--no-verify --signoff"
          commit_message: "ci: apply formatting changes"
